<?php

return [
    [
        'name' => 'version',
        'title' => 'API版本(请勿修改该值)',
        'type' => 'radio',
        'content' => [],
        'value' => 'v2',
        'rule' => '',
        'msg' => '',
        'tip' => 'V2版本只支持微信支付V2密钥，V3版本只支持微信支付V3密钥，请勿修改该值！！！',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wechat',
        'title' => '微信',
        'type' => 'array',
        'content' => [],
        'value' => [
            'appid' => '',
            'app_id' => 'wxa7e1223c29a5f66b',
            'app_secret' => '',
            'miniapp_id' => '',
            'mch_id' => '1664835371',
            'key' => 'sji2whjasnmo302jsdov24678WP5736Q',
            'key_v3' => 'cdfrscfs549783mokkiRH95lk65ShgG3',
            'mode' => 'normal',
            'sub_mch_id' => '',
            'sub_appid' => '',
            'sub_app_id' => '',
            'sub_miniapp_id' => '',
            'notify_url' => '',
            'cert_client' => '/addons/epay/certs/apiclient_cert.pem',
            'cert_key' => '/addons/epay/certs/apiclient_key.pem',
            'log' => '1',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '微信参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'alipay',
        'title' => '支付宝',
        'type' => 'array',
        'content' => [],
        'value' => [
            'mode' => 'normal',
            'pid' => '',
            'app_id' => '2021004129673938',
            'notify_url' => '/api/order/alipay_notify',
            'return_url' => '/addons/epay/api/returnx/type/alipay',
            'private_key' => 'MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCK+K1RmAw934NmttEmn76NM0djhoOYJ8fE5bVIoXXCrn72r3sA52xrVew7PAOe67mWyefVjE+T1DDKCJ+Hkm5UzZsxYKzzCmFwau72P69jZNMop5ITpGU3gwiSra4rT316hkxO/1QV2H0L7r2q9vL+h39f9Iyqshsayx1hZUn2tGb44BCpBxxKL6Kqple+YLwamUrdlgb4Laz+r6A+IHzhPHbtR8gnSds92vLyzlIZ2uwxudKqmVyr4wfX+WbKne6uAC38/MZjkxH9cvQEUdk+HQ3e2NSFSuG21MU2DmhHW39qQu4hEh1rH65TyQIBl6YKnMq+UD9RuaWrUlF9O0zfAgMBAAECggEAbjca/gMgclG53NRQu9klPsbUb1JXO20ROk8Tny6uPmA1wV8apnTjv5y9ZZ0LIhbBcZ1fiDVnR06aAyEjpFm1tvv5gQezIm2xKX8lVZbcem+UKEH90CYpQAVj3zBvWVoJogqwqlZFUa4IPlZxhg2kWckMdAV3KklmxbEg9AVoy4bFW4kmu30KX0Yme8zfhPJiIhRBqBipoHpURFl3qGIZFkdcH4lcjezT2ExplR9zTdDP6cCFH14DC1Z+74CDIK4/xYrT2XDN8qsr/07OgscejdyXavPIL4ZVKJ9+f/I3izYiJ+9YRyGWU5G18OnxXhqsCC8zAdbbxMGa40VhwvauAQKBgQDq4Azyu/GBCdRo66RvHPTPyNLd5LbQzRR4KSwN7eSwgudW989Gr4zN8VNEhNZSnpC9uk2mEHyAcTFC36jN2gf8QWz1rmz9pJV0FIpMGmPiUaB7Yb/3sq/tHTsmsCj0Jdg+RMqmJmZk6/r+TR2jR+282IYr4f+QxCw0WERxBTDl/wKBgQCXeHZuKrEZto/rDJM1u510/FuWFlVzbyCrZ1DC931lkJGivgEEK5r/zEXKZeLWKVngAL07OJNLEA2RFhsnfkV79euiCwCY7vA5+NpnILYLoAeZRKgTiXEMFtayqR5uvtH0cEnS//EK8PpSeItI7227eW5QwlbrVWqcwv8JXghZIQKBgQCYfVBKw9S+11ftqpe+gAk9Yf/tilFa7NrOTMTKYlooc0SpBQiwtsbu6jAKe0f+qe4FEBDbsTZz2YmHBli9FUI792o7c7xVTOavT6qeUD/rLt3HXSZaNcvcYS8HJjXglTV48Aa1qpauDTuOoRiN6uQhyF4L3ZWkMokUjv4YdqtRlwKBgF9PZ4YOyv2ZCJoogYDwGzX/jUm1p/NI28++5OypengsLdevo0gSgCexS8D9t2x2/JydGnVnNhendEH1HQUOyX4k0i5WqfuRbguscREvXh2WhvGEaBZTB5VJ0bL+A64/2DDtbyab8fqmg3zdaRdtwSiUUjvy7WqLhtg5Qu2MA8jBAoGAZo07jTqJsS2prwMnFfGSq29Bt71QsvMxtGaIr4JSiTrZiFSD3YKhyhZeG4kvlG9vYxdUgrQRlzM4K9Nx0BZlapbnXGl9Qwmj8P4zssplAh92Lenyz+ifXRSDTscBsziW6ICR7tD40ummlVYG0DL8DqnxJjlc5ZW1FnI5j8Xuc/M=',
            'signtype' => 'cert',
            'ali_public_key' => '/addons/epay/certs/alipayCertPublicKey_RSA2.crt',
            'app_cert_public_key' => '/addons/epay/certs/appCertPublicKey_2021004129673938.crt',
            'alipay_root_cert' => '/addons/epay/certs/alipayRootCert.crt',
            'log' => '1',
            'scanpay' => '1',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '支付宝参数配置',
        'ok' => '',
        'extend' => '',
    ],
];
