<?php

return [
    [
        'name' => 'appid',
        'title' => '应用AppID',
        'type' => 'string',
        'content' => [],
        'value' => '1400882339',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'appkey',
        'title' => '应用AppKEY',
        'type' => 'string',
        'content' => [],
        'value' => 'e9077a4ba9d4d255850840963582ac93',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'voiceAppid',
        'title' => '语音短信AppID',
        'type' => 'string',
        'content' => [],
        'value' => '1400882339',
        'rule' => 'required',
        'msg' => '使用语音短信必须设置',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'voiceAppkey',
        'title' => '语音短信AppKEY',
        'type' => 'string',
        'content' => [],
        'value' => 'e9077a4ba9d4d255850840963582ac93',
        'rule' => 'required',
        'msg' => '使用语音短信必须设置',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sign',
        'title' => '签名',
        'type' => 'string',
        'content' => [],
        'value' => '深圳市千千策科技',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'isVoice',
        'title' => '是否使用语音短信',
        'type' => 'radio',
        'content' => [
            '否',
            '是',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'isTemplateSender',
        'title' => '是否使用短信模板发送',
        'type' => 'radio',
        'content' => [
            '否',
            '是',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'template',
        'title' => '短信模板',
        'type' => 'array',
        'content' => [],
        'value' => [
            'login' => '2051425',
            'register' => '2051425',
            'resetpwd' => '2051425',
            'changepwd' => '2051425',
            'changemobile' => '2051425',
            'profile' => '2051425',
            'notice' => '2051449',
            'mobilelogin' => '2051425',
            'bind' => '2051425',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'voiceTemplate',
        'title' => '语音短信模板',
        'type' => 'array',
        'content' => [],
        'value' => [
            'register' => '',
            'resetpwd' => '',
            'changepwd' => '',
            'changemobile' => '',
            'profile' => '',
            'notice' => '',
            'mobilelogin' => '',
            'bind' => '',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
